import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manas Trivedi
 */
public class NITK_Virtual_Guide extends javax.swing.JFrame {
    DefaultTableModel newsTM = null;
    DefaultTableModel eventsTM = null;
    DefaultTableModel breakfastTM = null;
    DefaultTableModel lunchTM = null;
    DefaultTableModel dinnerTM = null;
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    String newsTitle = null;
    String newsDate = null;
    String eventTitle = null;
    String eventStartDate = null;
    String eventEndDate = null;
    /**
     * Creates new form NITK_Virtual_Guide
     */
    public NITK_Virtual_Guide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newsTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        eventsFrame = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        eventsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        menuFrame = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hostelBox = new javax.swing.JComboBox<>();
        dayNameLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        dinnerTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        breakfastTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        lunchTable = new javax.swing.JTable();
        menuGoButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        mapFrame = new javax.swing.JFrame();
        newsDetailsFrame = new javax.swing.JFrame();
        newsTitleLabel = new javax.swing.JLabel();
        newsDateLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newsContentTextArea = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        eventDetailsFrame = new javax.swing.JFrame();
        eventTitleLabel = new javax.swing.JLabel();
        eventStartDateLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventContentTextArea = new javax.swing.JTextArea();
        eventEndDateLabel = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        newsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        newsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        newsFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));
        newsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                newsFrameWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel1.setText("News");

        newsTable.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        newsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Date"
            }
        ));
        newsTable.setRowHeight(42);
        newsTable.setTableHeader(null);
        newsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(newsTable);

        jButton5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newsFrameLayout = new javax.swing.GroupLayout(newsFrame.getContentPane());
        newsFrame.getContentPane().setLayout(newsFrameLayout);
        newsFrameLayout.setHorizontalGroup(
            newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFrameLayout.createSequentialGroup()
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addGap(852, 852, 852)
                        .addComponent(jLabel1))
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        newsFrameLayout.setVerticalGroup(
            newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        eventsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        eventsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        eventsFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));
        eventsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                eventsFrameWindowActivated(evt);
            }
        });

        eventsTable.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        eventsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Start", "End"
            }
        ));
        eventsTable.setRowHeight(42);
        eventsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(eventsTable);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel4.setText("Events");

        jButton6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventsFrameLayout = new javax.swing.GroupLayout(eventsFrame.getContentPane());
        eventsFrame.getContentPane().setLayout(eventsFrameLayout);
        eventsFrameLayout.setHorizontalGroup(
            eventsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventsFrameLayout.createSequentialGroup()
                .addGroup(eventsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventsFrameLayout.createSequentialGroup()
                        .addGap(852, 852, 852)
                        .addComponent(jLabel4))
                    .addGroup(eventsFrameLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eventsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        eventsFrameLayout.setVerticalGroup(
            eventsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        menuFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        menuFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        menuFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));
        menuFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                menuFrameWindowActivated(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel3.setText("Mess Menu");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setText("Select hostel:");

        hostelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dayNameLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        dayNameLabel.setText("DayName");

        dinnerTable.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        dinnerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dinner"
            }
        ));
        dinnerTable.setRowHeight(36);
        jScrollPane6.setViewportView(dinnerTable);

        breakfastTable.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        breakfastTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Breakfast"
            }
        ));
        breakfastTable.setRowHeight(36);
        jScrollPane7.setViewportView(breakfastTable);

        lunchTable.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lunchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lunch"
            }
        ));
        lunchTable.setRowHeight(36);
        jScrollPane8.setViewportView(lunchTable);

        menuGoButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        menuGoButton.setText("Go");
        menuGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGoButtonActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuFrameLayout = new javax.swing.GroupLayout(menuFrame.getContentPane());
        menuFrame.getContentPane().setLayout(menuFrameLayout);
        menuFrameLayout.setHorizontalGroup(
            menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFrameLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(hostelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(menuGoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dayNameLabel)
                .addGap(133, 133, 133))
            .addGroup(menuFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(691, 691, 691)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuFrameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        menuFrameLayout.setVerticalGroup(
            menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFrameLayout.createSequentialGroup()
                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuFrameLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menuFrameLayout.createSequentialGroup()
                                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(hostelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayNameLabel)
                                    .addComponent(menuGoButton))
                                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuFrameLayout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuFrameLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        mapFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        mapFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        mapFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));

        javax.swing.GroupLayout mapFrameLayout = new javax.swing.GroupLayout(mapFrame.getContentPane());
        mapFrame.getContentPane().setLayout(mapFrameLayout);
        mapFrameLayout.setHorizontalGroup(
            mapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mapFrameLayout.setVerticalGroup(
            mapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        newsDetailsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        newsDetailsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        newsDetailsFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));
        newsDetailsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                newsDetailsFrameWindowActivated(evt);
            }
        });

        newsTitleLabel.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        newsTitleLabel.setText("News Title");

        newsDateLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newsDateLabel.setText("Date added:");

        newsContentTextArea.setEditable(false);
        newsContentTextArea.setColumns(20);
        newsContentTextArea.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        newsContentTextArea.setRows(5);
        jScrollPane2.setViewportView(newsContentTextArea);

        jButton8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newsDetailsFrameLayout = new javax.swing.GroupLayout(newsDetailsFrame.getContentPane());
        newsDetailsFrame.getContentPane().setLayout(newsDetailsFrameLayout);
        newsDetailsFrameLayout.setHorizontalGroup(
            newsDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsDetailsFrameLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(newsDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newsDetailsFrameLayout.createSequentialGroup()
                        .addGroup(newsDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newsDateLabel))
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(newsDetailsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newsDetailsFrameLayout.setVerticalGroup(
            newsDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsDetailsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(newsTitleLabel)
                .addGap(69, 69, 69)
                .addComponent(newsDateLabel)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        eventDetailsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        eventDetailsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        eventDetailsFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));
        eventDetailsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                eventDetailsFrameWindowActivated(evt);
            }
        });

        eventTitleLabel.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        eventTitleLabel.setText("Event Title");

        eventStartDateLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        eventStartDateLabel.setText("Start Date:");

        eventContentTextArea.setEditable(false);
        eventContentTextArea.setColumns(20);
        eventContentTextArea.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        eventContentTextArea.setRows(5);
        jScrollPane3.setViewportView(eventContentTextArea);

        eventEndDateLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        eventEndDateLabel.setText("End Date:");

        jButton9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventDetailsFrameLayout = new javax.swing.GroupLayout(eventDetailsFrame.getContentPane());
        eventDetailsFrame.getContentPane().setLayout(eventDetailsFrameLayout);
        eventDetailsFrameLayout.setHorizontalGroup(
            eventDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventDetailsFrameLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(eventDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(eventDetailsFrameLayout.createSequentialGroup()
                        .addGroup(eventDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(eventDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(eventEndDateLabel)
                                .addComponent(eventStartDateLabel)))
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(eventDetailsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eventDetailsFrameLayout.setVerticalGroup(
            eventDetailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventDetailsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(eventTitleLabel)
                .addGap(69, 69, 69)
                .addComponent(eventStartDateLabel)
                .addGap(18, 18, 18)
                .addComponent(eventEndDateLabel)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1837, 1055));
        setPreferredSize(new java.awt.Dimension(1837, 1055));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 60)); // NOI18N
        jLabel2.setText("NITK Virtual Guide");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jButton1.setText("News");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jButton2.setText("Events");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jButton4.setText("Map");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(725, 725, 725))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 561, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(430, 430, 430))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel2)
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        newsFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        eventsFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        menuFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        mapFrame.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_newsFrameWindowActivated
        newsTM = (DefaultTableModel)newsTable.getModel();
        newsTM.setRowCount(0);
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/NITK_Virtual_Guide", "root", "1234");
            stmt = con.createStatement();
            sql = "SELECT Title, Date FROM News ORDER BY Date DESC;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                newsTM.addRow(new Object [] {rs.getString("Title"), rs.getString("Date")});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_newsFrameWindowActivated

    private void newsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsTableMouseClicked
        newsTitle = (String)newsTM.getValueAt(newsTable.getSelectedRow(), 0);
        newsDate = (String)newsTM.getValueAt(newsTable.getSelectedRow(), 1);
        newsDetailsFrame.setVisible(true);
        newsFrame.dispose();
    }//GEN-LAST:event_newsTableMouseClicked

    private void newsDetailsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_newsDetailsFrameWindowActivated
        newsTitleLabel.setText(newsTitle);
        newsDateLabel.setText("Date added: " + newsDate);
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/NITK_Virtual_Guide", "root", "1234");
            stmt = con.createStatement();
            sql = "SELECT Content FROM News WHERE Title = '" + newsTitle + "' AND Date = '" + newsDate + "';";
            rs = stmt.executeQuery(sql);
            rs.first();
            newsContentTextArea.setText(rs.getString("Content"));
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_newsDetailsFrameWindowActivated

    private void eventsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsTableMouseClicked
        eventTitle = (String)eventsTM.getValueAt(eventsTable.getSelectedRow(), 0);
        eventStartDate = (String)eventsTM.getValueAt(eventsTable.getSelectedRow(), 1);
        eventEndDate = (String)eventsTM.getValueAt(eventsTable.getSelectedRow(), 2);
        eventDetailsFrame.setVisible(true);
        eventsFrame.dispose();
    }//GEN-LAST:event_eventsTableMouseClicked

    private void eventsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_eventsFrameWindowActivated
        JTableHeader tableHeader = eventsTable.getTableHeader();
        Font headerFont = new Font("Calibri", Font.PLAIN, 24);
        tableHeader.setFont(headerFont);
        eventsTM = (DefaultTableModel)eventsTable.getModel();
        eventsTM.setRowCount(0);
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/NITK_Virtual_Guide", "root", "1234");
            stmt = con.createStatement();
            sql = "SELECT Title, StartDate, EndDate FROM Events WHERE EndDate >= curdate() ORDER BY StartDate ASC;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                eventsTM.addRow(new Object [] {rs.getString("Title"), rs.getString("StartDate"), rs.getString("EndDate")});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_eventsFrameWindowActivated

    private void eventDetailsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_eventDetailsFrameWindowActivated
        eventTitleLabel.setText(eventTitle);
        eventStartDateLabel.setText("Start Date: " + eventStartDate);
        eventEndDateLabel.setText("End Date: " + eventEndDate);
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/NITK_Virtual_Guide", "root", "1234");
            stmt = con.createStatement();
            sql = "SELECT Content FROM Events WHERE Title = '" + eventTitle + "' AND StartDate = '" + eventStartDate + "' AND EndDate = '" + eventEndDate + "';";
            rs = stmt.executeQuery(sql);
            rs.first();
            eventContentTextArea.setText(rs.getString("Content"));
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_eventDetailsFrameWindowActivated

    private void menuFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_menuFrameWindowActivated
        JTableHeader breakfastTableHeader = breakfastTable.getTableHeader();
        JTableHeader lunchTableHeader = lunchTable.getTableHeader();
        JTableHeader dinnerTableHeader = dinnerTable.getTableHeader();
        Font headerFont = new Font("Calibri", Font.PLAIN, 24);
        breakfastTableHeader.setFont(headerFont);
        lunchTableHeader.setFont(headerFont);
        dinnerTableHeader.setFont(headerFont);
        breakfastTM = (DefaultTableModel)breakfastTable.getModel();
        lunchTM = (DefaultTableModel)lunchTable.getModel();
        dinnerTM = (DefaultTableModel)dinnerTable.getModel();
        breakfastTM.setRowCount(0);
        lunchTM.setRowCount(0);
        dinnerTM.setRowCount(0);
        hostelBox.removeAllItems();
        hostelBox.addItem("--Select--");
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/NITK_Virtual_Guide", "root", "1234");
            stmt = con.createStatement();
            sql = "SELECT DAYNAME(curdate());";
            rs = stmt.executeQuery(sql);
            rs.first();
            dayNameLabel.setText(rs.getString(1));
            sql = "SELECT DISTINCT Hostel FROM Menu;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                hostelBox.addItem(rs.getString("Hostel"));
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuFrameWindowActivated

    private void menuGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGoButtonActionPerformed
        breakfastTM.setRowCount(0);
        lunchTM.setRowCount(0);
        dinnerTM.setRowCount(0);
        if(hostelBox.getSelectedIndex() == 0 || hostelBox.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Please select a hostel.");
            return;
        }
        String hostelName = (String)hostelBox.getSelectedItem();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/NITK_Virtual_Guide", "root", "1234");
            stmt = con.createStatement();
            sql = "SELECT Item FROM Menu WHERE Hostel = '" + hostelName + "' AND Day = DAYNAME(curdate()) AND Meal = 'Breakfast';";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                breakfastTM.addRow(new Object [] {rs.getString("Item")});
            }
            sql = "SELECT Item FROM Menu WHERE Hostel = '" + hostelName + "' AND Day = DAYNAME(curdate()) AND Meal = 'Lunch';";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                breakfastTM.addRow(new Object [] {rs.getString("Item")});
            }
            sql = "SELECT Item FROM Menu WHERE Hostel = '" + hostelName + "' AND Day = DAYNAME(curdate()) AND Meal = 'Dinner';";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                breakfastTM.addRow(new Object [] {rs.getString("Item")});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuGoButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        newsFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        eventsFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        menuFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        newsDetailsFrame.dispose();
        newsFrame.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        eventDetailsFrame.dispose();
        eventsFrame.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NITK_Virtual_Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NITK_Virtual_Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NITK_Virtual_Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NITK_Virtual_Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NITK_Virtual_Guide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable breakfastTable;
    private javax.swing.JLabel dayNameLabel;
    private javax.swing.JTable dinnerTable;
    private javax.swing.JTextArea eventContentTextArea;
    private javax.swing.JFrame eventDetailsFrame;
    private javax.swing.JLabel eventEndDateLabel;
    private javax.swing.JLabel eventStartDateLabel;
    private javax.swing.JLabel eventTitleLabel;
    private javax.swing.JFrame eventsFrame;
    private javax.swing.JTable eventsTable;
    private javax.swing.JComboBox<String> hostelBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable lunchTable;
    private javax.swing.JFrame mapFrame;
    private javax.swing.JFrame menuFrame;
    private javax.swing.JButton menuGoButton;
    private javax.swing.JTextArea newsContentTextArea;
    private javax.swing.JLabel newsDateLabel;
    private javax.swing.JFrame newsDetailsFrame;
    private javax.swing.JFrame newsFrame;
    private javax.swing.JTable newsTable;
    private javax.swing.JLabel newsTitleLabel;
    // End of variables declaration//GEN-END:variables
}
